name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Compile Beamer
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            main.tex
            main-en.tex
          work_in_root_file_dir: true

      - name: "Git artifact: PDF"
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            main.pdf
            main-en.pdf
